use mysql;
CREATE USER XXXXDB_UXXXX@'localhost' IDENTIFIED WITH caching_sha2_password BY 'XXXXDB_PXXXX' REQUIRE SSL;
CREATE USER XXXXDB_UXXXX@'127.0.0.1' IDENTIFIED WITH caching_sha2_password BY 'XXXXDB_PXXXX' REQUIRE SSL;
CREATE USER XXXXDB_UXXXX@'XXXXIP_MASKXXXX' IDENTIFIED WITH caching_sha2_password BY 'XXXXDB_PXXXX' REQUIRE SSL;
CREATE USER XXXXDB_UXXXX_install@'localhost' IDENTIFIED WITH caching_sha2_password BY 'XXXXDB_PXXXX';
CREATE USER XXXXDB_UXXXX_install@'127.0.0.1' IDENTIFIED WITH caching_sha2_password BY 'XXXXDB_PXXXX';
CREATE USER XXXXDB_UXXXX_install@'XXXXIP_MASKXXXX' IDENTIFIED WITH caching_sha2_password BY 'XXXXDB_PXXXX';

/* Having a root user is disabled by default if you want one for your deployment uncomment these lines and the GRANT ALL PRIVILEGES lines below
CREATE USER XXXXDB_UXXXX_root@'localhost' IDENTIFIED WITH caching_sha2_password BY 'XXXXDB_PXXXX' REQUIRE SSL;
CREATE USER XXXXDB_UXXXX_root@'127.0.0.1' IDENTIFIED WITH caching_sha2_password BY 'XXXXDB_PXXXX' REQUIRE SSL; */

DROP DATABASE IF EXISTS XXXXDB_NXXXX;
create database XXXXDB_NXXXX;
ALTER DATABASE XXXXDB_NXXXX CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP. ALTER, LOCK TABLES ON XXXXDB_NXXXX.* TO XXXXDB_UXXXX@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, LOCK TABLES ON XXXXDB_NXXXX.* TO XXXXDB_UXXXX@'127.0.0.1';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, LOCK TABLES ON XXXXDB_NXXXX.* TO XXXXDB_UXXXX@'XXXXIP_MASKXXXX';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, LOCK TABLES ON XXXXDB_NXXXX.* TO XXXXDB_UXXXX_install@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, LOCK TABLES ON XXXXDB_NXXXX.* TO XXXXDB_UXXXX_install@'127.0.0.1';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, LOCK TABLES ON XXXXDB_NXXXX.* TO XXXXDB_UXXXX_install@'XXXXIP_MASKXXXX';
/*GRANT ALL PRIVILEGES ON *.* TO XXXXDB_UXXXX_root@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO XXXXDB_UXXXX_root@'127.0.0.1' WITH GRANT OPTION;*/

DROP DATABASE IF EXISTS test;
DROP USER IF EXISTS 'mysql'@'localhost';
DROP USER IF EXISTS 'root'@'localhost';
flush privileges;
