use mysql;
SET sql_require_primary_key=0;
CREATE USER 'XXXXDB_UXXXX'@'%' IDENTIFIED BY 'XXXXDB_PXXXX' REQUIRE SSL;
CREATE USER 'XXXXDB_UXXXX_notls'@'%' IDENTIFIED BY 'XXXXDB_PXXXX';
flush privileges;

